const labels: Record<string, string> = {
  'Software engineering': 'Разработка программного обеспечения',
  'AI & data': 'ИИ и анализ данных',
  Cybersecurity: 'Кибербезопасность',
  'Any city': 'Любой город',
  Astana: 'Астана',
  Almaty: 'Алматы',
  Karaganda: 'Караганда',
  Shymkent: 'Шымкент',
  'Other city': 'Другой город',
  Kazakhstan: 'Казахстан',
  Mathematics: 'Математика',
  Programming: 'Программирование',
  English: 'Английский',
  Writing: 'Письмо',
  Research: 'Исследования',
  Teamwork: 'Командная работа',
  Hackathons: 'Хакатоны',
  Volunteering: 'Волонтёрство',
  'Personal Projects': 'Личные проекты',
  Competitions: 'Олимпиады и конкурсы',
  Leadership: 'Лидерство',
  Dream: 'Мечта',
  Priority: 'Цель',
  Backup: 'Запасной вариант',
  Considering: 'Цель',
  UNT: 'ЕНТ',
  SAT: 'SAT',
  IELTS: 'IELTS',
  NUET: 'NUET',
  AET: 'AET',
  Now: 'Сейчас',
  Prepare: 'Подготовка',
  Apply: 'Подача документов',
  Confirm: 'Зачисление',
  unknown: 'Не указано',
  planned: 'Запланировано',
  'in-progress': 'В работе',
  completed: 'Готово',
  'not-planned': 'Не планирую',
  'Fits your verified budget': 'В пределах подтверждённого бюджета',
  'Needs verification': 'Нужно уточнить',
  'Over budget': 'Выше бюджета',
  Listening: 'Аудирование',
  Reading: 'Чтение',
  Speaking: 'Устная речь',
  any: 'Любой язык',
  ru: 'Русский',
  kk: 'Казахский',
  en: 'Английский',
  excellent: 'Отличная',
  good: 'Хорошая',
  'needs-support': 'Нужна поддержка',
  self: 'Платное обучение',
  grant: 'Грант',
  either: 'Рассматриваю оба варианта',
  domestic: 'Гражданин Казахстана',
  international: 'Иностранный абитуриент',
  verified: 'Подтверждено источником',
  demo: 'Демонстрационные данные',
  bachelor: 'Бакалавриат',
  light: 'Светлая',
  dark: 'Тёмная',
  system: 'Как в системе',
}
export const ru = (value: string): string => labels[value] ?? value
