import { test, expect } from '@playwright/test'

test('full journey, comparison, persistence and profile changes', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Всё начинается с тебя.' })).toBeVisible()
  await page.screenshot({ path: `tmp/screenshots/${testInfo.project.name}-overview.png`, fullPage: true })
  await page.getByRole('button', { name: 'Построить мой маршрут', exact: true }).click()
  await page.getByLabel('Как тебя зовут?').fill('Дана')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByLabel('Средний балл').fill('4.8')
  await page.getByLabel('Текущий результат IELTS').selectOption('7')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByRole('button', { name: 'Германия', exact: true }).click()
  await page.getByRole('button', { name: 'Нидерланды', exact: true }).click()
  await page.getByRole('button', { name: 'Казахстан', exact: true }).click()
  await page.getByLabel('Бюджет на обучение в год').fill('5000')
  await page.getByRole('button', { name: 'Построить маршрут', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Дана', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Посмотреть подборку' }).click()
  await expect(page.locator('.program-card').first()).toContainText('Steppe Technology University')
  await page.locator('.compare-toggle').nth(0).click()
  await page.locator('.compare-toggle').nth(1).click()
  await page.getByRole('button', { name: 'Сравнить программы', exact: true }).click()
  await expect(page.locator('.comparison-table')).toBeVisible()
  await expect(page.locator('.comparison-table thead th')).toHaveCount(3)
  await page.getByRole('button', { name: 'Выбрать программу' }).first().click()
  await expect(page.getByRole('heading', { name: 'Твой маршрут поступления.' })).toBeVisible()
  await page.locator('.task-check').first().click()
  await expect(page.locator('.task-check').first()).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.locator('.task-check').first()).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.roadmap-target')).toContainText('Steppe Technology University')
  await page.screenshot({ path: `tmp/screenshots/${testInfo.project.name}-roadmap.png`, fullPage: true })
  await page.getByRole('button', { name: 'Редактировать профиль', exact: true }).click()
  await page.getByRole('button', { name: 'Бизнес и экономика' }).click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByRole('button', { name: 'Построить маршрут', exact: true }).click()
  await page.getByRole('button', { name: 'Посмотреть подборку' }).click()
  await expect(page.locator('.program-card').first()).toContainText('Altai Applied University')
  await page.getByRole('textbox', { name: 'Поиск программ' }).fill('zzzzzz')
  await expect(page.getByRole('heading', { name: 'Пока ничего не нашлось' })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await expect(page.locator('.program-card')).toHaveCount(9)
  expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('form validates empty countries and dialog closes with Escape', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Построить мой маршрут', exact: true }).click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByRole('button', { name: 'Германия', exact: true }).click()
  await page.getByRole('button', { name: 'Нидерланды', exact: true }).click()
  await page.getByRole('button', { name: 'Построить маршрут', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Выбери хотя бы одну страну')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('production health endpoint and unknown assets', async ({ request }) => {
  expect((await request.get('/health')).status()).toBe(200)
  expect((await request.get('/assets/missing.js')).status()).toBe(404)
  expect((await request.get('/any-client-route', { headers: { Accept: 'text/html' } })).status()).toBe(200)
})
